import type { Metadata } from 'next';
import { IBM_Plex_Mono, VT323 } from 'next/font/google';
import './globals.css';
// import Navbar from './components/Navbar';

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const vt323 = VT323({
  variable: '--font-vt323',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`md:p-5 bg-black ${ibmPlexMono.variable} ${vt323.variable} antialiased max-w-[125rem] mx-auto`}
      >
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
