import type { Metadata } from 'next';
import { IBM_Plex_Mono, VT323, Source_Sans_3 } from 'next/font/google';
import './globals.css';

const ibmPlexMono = IBM_Plex_Mono({
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const vt323 = VT323({
  variable: '--font-vt323',
  subsets: ['latin'],
  weight: ['400'],
});

const sourceSansPro = Source_Sans_3({
  variable: '--font-source-sans-pro',
  subsets: ['latin'],
  weight: ['400', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`h-full md:p-5 bg-black ${ibmPlexMono.variable} ${vt323.variable} ${sourceSansPro.variable} antialiased max-w-[125rem] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
